{%block content %}{% endblock %}
{{ full_content }}


--------------------------------------------------
Este texto es material ficticio parte del
juego {{ campaign_name }} en {{ server_name }}.
CC-BY-SA, sus contribuciones serán adjudicadas
como {{ attribution }}. Ud. puede cambiar esto
enviando un correo electrónico a
pm-new-attribution@{{ server_name }}
especificando en el asunto la nueva adjudicación.
